### ISSUE TITLE
健康診断結果報告書の仕様書βとの比較

### ISSUE THREAD

**Issue by hosanai** [HealthDataWorks/fhir-ig-jp-specific-health-checkups#3]
以下で健康診断結果報告書の仕様書βが公開されました。本実装ガイドとの比較が必要(Bundleを使っている模様)

https://std.jpfhir.jp/
健康診断結果報告書FHIR®記述仕様書案β の公開

**Comment by hosanai** [comment]
健康診断結果報告書と特定健診の比較整理、また、内容についての議論をまとめた資料を添付します。この内容で実装ガイドの修正を実施しましょう。
[健康診断結果報告書と特定健診のFHIRリソース比較.xlsx](https://github.com/HealthDataWorks/fhir-ig-jp-specific-health-checkups/files/6592039/FHIR.xlsx)

**Comment by ns0602yk** [comment]
資料 健康診断結果報告書と特定健診のFHIRリソース比較.xlsx の内容にしたがって実装ガイドを修正しました
